### ISSUE TITLE
[Need Update]

### ISSUE THREAD

**Issue by sht2017** [MHST2Modding/MHS2Loader#1]
Glad to see here's a mod loader for MHS2 but unfortunately, it seems out of date so far.

**Comment by DoLLo73** [comment]
+1

**Comment by ruvaldak** [comment]
I contacted the dev and he said he'd work on an update this thanksgiving/weekend.

**Comment by Andoryuuta** [comment]
Yes, I'll try to get it updated this thanksgiving.

**Comment by ruvaldak** [comment]
How's progress on this going?

**Comment by Andoryuuta** [comment]
Resolved in dcd82c6, new release at https://github.com/MHST2Modding/MHS2Loader/releases/tag/v4.0.0.
